"""Rename medical_license to rut in Doctor model

Revision ID: 5af46148d926
Revises: 5f24a15b6f2d
Create Date: 2025-11-04 00:22:25.215275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5af46148d926'
down_revision = '5f24a15b6f2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rut', sa.String(length=12), nullable=True))
        batch_op.drop_column('medical_license')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medical_license', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('rut')

    # ### end Alembic commands ###
