"""add_original_fpa_fields

Revision ID: 268afe8e7a1f
Revises: 8367ec62efae
Create Date: 2026-02-11 00:49:44.338700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268afe8e7a1f'
down_revision = '8367ec62efae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_overnight_stays', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('original_fpa_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('original_fpa_date')
        batch_op.drop_column('original_overnight_stays')

    # ### end Alembic commands ###
