"""Move room from Patient to Ticket

Revision ID: 5f24a15b6f2d
Revises: 78202ac7184e
Create Date: 2025-10-26 12:25:48.380219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f24a15b6f2d'
down_revision = '78202ac7184e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room', sa.String(length=100), nullable=True))

    # ### Custom data migration ###
    op.execute('''
        UPDATE ticket
        SET room = (
            SELECT patient.room
            FROM patient
            WHERE patient.id = ticket.patient_id
        )
    ''')
    # ### End Custom data migration ###

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('room')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### Custom data migration (best effort) ###
    op.execute('''
        UPDATE patient
        SET room = (
            SELECT ticket.room
            FROM ticket
            WHERE ticket.patient_id = patient.id
            ORDER BY ticket.created_at DESC
            LIMIT 1
        )
    ''')
    # ### End Custom data migration ###

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('room')
    # ### end Alembic commands ###
