"""Add Superuser table

Revision ID: a1b2c3d4e5f6
Revises: bdde3be33136
Create Date: 2025-10-20 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'bdde3be33136'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    superuser_table = op.create_table('superuser',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )

    # Seed initial superuser
    op.bulk_insert(superuser_table,
        [
            {'email': 'admin_prov@tickethome.com'}
        ]
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('superuser')
    # ### end Alembic commands ###
