"""Make User.clinic_id nullable for superuser role

Revision ID: bc4a869c97f1
Revises: d67d83c95861
Create Date: 2025-10-24 00:06:17.264777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc4a869c97f1'
down_revision = 'd67d83c95861'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('clinic_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('clinic_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
