"""Add UrgencyThreshold table for configurable ticket color thresholds

Revision ID: e7f8g9h0i1j2
Revises: a1b2c3d4e5f6
Create Date: 2025-11-09 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime

# revision identifiers, used by Alembic.
revision = 'e7f8g9h0i1j2'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    urgency_threshold_table = op.create_table('urgency_threshold',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('clinic_id', sa.Integer(), nullable=True),
        sa.Column('green_threshold_hours', sa.Integer(), nullable=False, server_default='8'),
        sa.Column('yellow_threshold_hours', sa.Integer(), nullable=False, server_default='4'),
        sa.Column('red_threshold_hours', sa.Integer(), nullable=False, server_default='2'),
        sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('updated_by', sa.String(length=80), nullable=True),
        sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # Seed default global configuration
    op.bulk_insert(urgency_threshold_table,
        [
            {
                'clinic_id': None,
                'green_threshold_hours': 8,
                'yellow_threshold_hours': 4,
                'red_threshold_hours': 2,
                'created_at': datetime.utcnow(),
                'updated_at': datetime.utcnow(),
                'updated_by': 'system'
            }
        ]
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('urgency_threshold')
    # ### end Alembic commands ###
